Repository c2corg/c2c_tracking, pull requests merged in 2022-11, with the labels that each got.

#560 feat!: exchange token doesn't redirect anymore
  src/auth/index.ts
  src/errors.ts
  src/server/decathlon/decathlon.controller.ts
  src/server/decathlon/decathlon.service.ts
  src/server/error-handler.ts
  src/server/garmin/garmin.controller.ts
  src/server/garmin/garmin.service.ts
  src/server/strava/strava.controller.ts
  src/server/strava/strava.service.ts
  src/server/suunto/suunto.controller.ts
  src/server/suunto/suunto.service.ts
  test/unit/auth/index.spec.ts
  test/unit/server/decathlon/decathlon.controller.spec.ts
  test/unit/server/garmin/garmin.controller.spec.ts
  test/unit/server/strava/strava.controller.spec.ts
  test/unit/server/suunto/suunto.controller.spec.ts
Labels: enhancement, breaking

#562 feat: add version information in health endpoint
  src/health.service.ts
  test/unit/health.service.spec.ts
  test/unit/server/health/health.controller.spec.ts
Labels: enhancement

#563 fix!: correctly format translations
  src/server/activities/activity.service.ts
  test/unit/server/activities/activity.service.spec.ts
Labels: bug, breaking

#565 feat: use strava sport_type instead of deprecated type
  src/helpers/i18n/ca.json
  src/helpers/i18n/de.json
  src/helpers/i18n/en.json
  src/helpers/i18n/es.json
  src/helpers/i18n/eu.json
  src/helpers/i18n/fr.json
  src/helpers/i18n/hu.json
  src/helpers/i18n/it.json
  src/helpers/i18n/ru.json
  src/helpers/i18n/sl.json
  src/helpers/i18n/zh_CN.json
  src/server/strava/strava.api.ts
  src/server/strava/strava.service.ts
  test/unit/server/strava/strava.api.spec.ts
  test/unit/server/strava/strava.service.spec.ts
Labels: enhancement, i18n

#569 feat: include vendorId in activities list
  src/server/activities/activity.service.ts
  test/unit/server/activities/activity.controller.spec.ts
  test/unit/server/activities/activity.service.spec.ts
Labels: enhancement

#578 fix: set npm_package_version in image
  .github/workflows/ci.yml
  Dockerfile
Labels: bug

#582 fix: knex transaction use
  src/repository/activity.repository.ts
Labels: bug

#581 chore: remove useless debug log
  src/user.service.ts
Labels: chore

#580 fix: Strava activity stream API request parameters
  src/server/strava/strava.api.ts
  test/unit/server/strava/strava.api.spec.ts
Labels: bug

#585 fix: Garmin connection process
  src/server/garmin/garmin.controller.ts
  test/unit/server/garmin/garmin.controller.spec.ts
Labels: bug

#586 fix: add metrics server to graceful shutdown
  src/index.ts
Labels: bug

#588 fix: Suunto API workout format
  src/helpers/error.ts
  src/server/suunto/suunto.api.ts
  test/unit/server/suunto/suunto.api.spec.ts
  test/unit/server/suunto/suunto.service.spec.ts
Labels: bug

#589 fix: do not try to parse arraybuffer response with zod
  src/server/suunto/suunto.api.ts
  test/unit/server/suunto/suunto.api.spec.ts
Labels: bug

#591 fix: relax constraints on activity types
  src/helpers/i18n/ca.json
  src/helpers/i18n/de.json
  src/helpers/i18n/en.json
  src/helpers/i18n/es.json
  src/helpers/i18n/eu.json
  src/helpers/i18n/fr.json
  src/helpers/i18n/hu.json
  src/helpers/i18n/it.json
  src/helpers/i18n/ru.json
  src/helpers/i18n/sl.json
  src/helpers/i18n/zh_CN.json
  src/server/decathlon/decathlon.service.ts
  src/server/garmin/garmin.api.ts
  src/server/strava/strava.api.ts
  src/server/suunto/suunto.service.ts
Labels: bug

#592 feat: filter out /health calls from API call logs
  src/app.ts
Labels: enhancement

#595 fix: correctly check Suunto webhook auth
  src/server/suunto/suunto.service.ts
  src/server/suunto/suunto.validators.ts
  test/unit/server/suunto/suunto.service.spec.ts
Labels: bug

#596 feat: add more log for external apis errors
  src/helpers/error.ts
Labels: chore

#597 fix: incorrect Strava webhook request creation response format
  src/server/strava/strava.api.ts
  src/server/strava/strava.service.ts
  test/unit/server/strava/strava.api.spec.ts
  test/unit/server/strava/strava.service.spec.ts
Labels: bug

#604 chore: use docker meta action output for setting version
  .github/workflows/ci.yml
Labels: chore

#605 feat: use local date
  src/server/garmin/garmin.api.ts
  src/server/garmin/garmin.service.ts
  src/server/strava/strava.api.ts
  src/server/strava/strava.service.ts
  src/server/suunto/suunto.service.ts
  test/unit/server/garmin/garmin.service.spec.ts
  test/unit/server/strava/strava.api.spec.ts
  test/unit/server/strava/strava.service.spec.ts
  test/unit/server/suunto/suunto.service.spec.ts
Labels: enhancement

#606 chore: remove useless dependency
  package-lock.json
  package.json
Labels: chore

#609 chore(config)!: use `trackers` in path instead of `external-services`
  src/config.ts
Labels: breaking, chore

#610 feat!: use frontend base URL as CORS allowed origin
  src/app.ts
Labels: breaking, chore

#613 feat(db): allow to specify DB schema
  src/config.ts
  src/db/index.ts
  src/db/migrations/20210506103300_create_schema.ts
  src/db/migrations/20220802100000_garmin.ts
  src/db/migrations/20221020000000_decathlon.ts
  src/db/migrations/20221104000000_activity_details.ts
  src/repository/activity.repository.ts
  src/repository/strava.repository.ts
  src/repository/user.repository.ts
Labels: enhancement

#617 bug: handle missing activity data
  src/server/strava/strava.service.ts
  src/server/suunto/suunto.api.ts
  src/server/suunto/suunto.service.ts
Labels: bug

#618 feat: default to english if no translation is available in target language
  src/server/activities/activity.service.ts
Labels: enhancement, i18n

#620 chore: fix strava test
  test/unit/server/strava/strava.service.spec.ts
Labels: chore

#621 bug: signature header is not required for Polar webhook PING
  src/server/polar/polar.validators.ts
Labels: bug

#622 bug: polar fixes
  src/db/migrations/20221122000000_polar_webhook_secret.ts
  src/server/polar/polar.api.ts
  src/server/polar/polar.service.ts
  test/unit/server/polar/polar.api.spec.ts
  test/unit/server/polar/polar.service.spec.ts
Labels: bug

#623 bug: remove final slash from CORS origin
  src/app.ts
Labels: bug

#624 bug: fix typo for setting allowed origin
  src/app.ts
Labels: bug

#625 bug: fix Polar API URLs
  src/server/polar/polar.api.ts
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#626 bug: use x-www-form-urlencoded for polar exchange token
  src/server/decathlon/decathlon.api.ts
  src/server/polar/polar.api.ts
  test/unit/server/decathlon/decathlon.api.spec.ts
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#627 fix(polar): use `redirect_uri` instead of `redirect_url`
  src/server/polar/polar.api.ts
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#628 fix(polar): ignore register result if user is already registered
  src/server/polar/polar.api.ts
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#629 fix(test): typo
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#630 fix(polar): handle register 409 code properly
  src/server/polar/polar.api.ts
  test/unit/server/polar/polar.api.spec.ts
Labels: bug

#635 fix(strava): remove dead (and falsy) code
  package-lock.json
  package.json
  src/server/activities/activity.service.ts
  src/server/strava/strava.api.ts
  src/server/strava/strava.service.ts
  test/unit/server/strava/strava.api.spec.ts
  test/unit/server/strava/strava.service.spec.ts
Labels: bug
